vcweb/core/subjectpool/urls.py
from django.conf.urls import url

from .views import (subjectpool_index, manage_experiment_session, get_session_events, manage_participant_attendance,
                    send_invitations, get_invitations_count, invite_email_preview, experiment_session_signup,
                    submit_experiment_session_signup, cancel_experiment_session_signup, download_experiment_session,
                    add_participant)

urlpatterns = [
    url(r'^$', subjectpool_index, name='subjectpool_index'),
    url(r'^session/manage/(?P<pk>\-?\d+)$', manage_experiment_session, name='manage_experiment_session'),
    url(r'^session/detail/event/(?P<pk>\d+)$', manage_participant_attendance, name='session_event_detail'),
    url(r'^session/(?P<pk>\d+)/participant/add/$', add_participant, name='add_participant'),
    url(r'^session/invite$', send_invitations, name='send_invites'),
    url(r'^session/invite/count$', get_invitations_count, name='get_invitations_count'),
    url(r'^session/email-preview$', invite_email_preview, name='invite_email_preview'),
    url(r'^session/(?P<pk>\d+)/download/$', download_experiment_session, name='download_experiment_session'),
    url(r'^session/events$', get_session_events, name='session_events'),

    url(r'^signup/$', experiment_session_signup, name='experiment_session_signup'),
    url(r'^signup/submit/$', submit_experiment_session_signup, name='submit_experiment_session_signup'),
    url(r'^signup/cancel/$', cancel_experiment_session_signup, name='cancel_experiment_session_signup'),
]

vcweb/core/urls.py
import logging

from django.conf.urls import url
from django.views.generic import RedirectView, TemplateView
from rest_framework import routers

from . import views
from .api import (get_round_data, save_experimenter_notes, create_experiment, clone_experiment, is_email_available,
                  handle_chat_message, check_ready_participants, participant_ready, )
from .views import (dashboard, LoginView, LogoutView, monitor, RegisterEmailListView, RegisterTestParticipantsView,
                    completed_survey, toggle_bookmark_experiment_metadata, check_survey_completed, ParticipateView,
                    download_data, download_participants, export_configuration, get_dashboard_view_model,
                    update_experiment, update_round_configuration, show_experiment_configuration,
                    edit_experiment_configuration, delete_experiment_configuration, clone_experiment_configuration,
                    unsubscribe, update_round_param_value, update_experiment_param_value,
                    update_experiment_configuration, OstromlabFaqList, cas_asu_registration,
                    cas_asu_registration_submit, account_profile, update_account_profile, update_participants,
                    audit_report)

logger = logging.getLogger(__name__)

'''
URLs for core vcweb app
'''
urlpatterns = [
    url(r'^cas/asu/$', cas_asu_registration, name='cas_asu_registration'),
    url(r'^cas/asu/submit/$', cas_asu_registration_submit, name='cas_asu_registration_submit'),
    url(r'^papers/$', TemplateView.as_view(template_name='papers.html')),
    url(r'^dashboard/$', dashboard, name='dashboard'),
    url(r'^accounts/login/$', LoginView.as_view(), name='login'),
    url(r'^accounts/logout/$', LogoutView.as_view(), name='logout'),
    # url(r'^accounts/add/$', RegistrationView.as_view(), name='register'), # XXX: open registration currently disabled
    url(r'^accounts/profile/$', account_profile, name='profile'),
    url(r'^accounts/mars-signup/$', views.PortOfMarsSignupView.as_view(), name='mars_registration'),
    url(r'^accounts/profile/update$', update_account_profile, name='update_profile'),
    url(r'^accounts/check-email$', is_email_available, name='check_email'),
    url(r'^ostromlab/faq/$', OstromlabFaqList.as_view(), name='ostromlab_faq'),
    url(r'^accounts/unsubscribe$', unsubscribe, name='unsubscribe'),
    url(r'^admin/audit-report$', audit_report, name='audit_report'),
    url(r'^participate/?$', ParticipateView.as_view(), name='participate'),
    url(r'^participate/survey-completed', completed_survey, name='survey_completed'),
    url(r'^participate/(?P<pk>\d+)/check-survey-completed', check_survey_completed, name='check_survey_completed'),
    url(r'^experiment/(?P<pk>\d+)/update-participants$', update_participants, name='update_participant'),
    url(r'^experiment/(?P<pk>\d+)/monitor$', monitor, name='monitor_experiment'),
    url(r'^experiment/(?P<pk>\d+)/register-email-list$', RegisterEmailListView.as_view(), name='register_email_list'),
    url(r'^experiment/(?P<pk>\d+)/register-test-participants$', RegisterTestParticipantsView.as_view(),
        name='register_test_participants'),
    url(r'^experiment/(?P<pk>\d+)/download/(?P<file_type>[\w]+)$', download_data, name='download_data'),
    url(r'^experiment/(?P<pk>\d+)/download-participants/$', download_participants, name='download_participants'),
    url(r'^experiment/(?P<pk>\d+)/export/configuration(?P<file_extension>.[\w]+)$', export_configuration,
        name='export_configuration'),
    url(r'^configuration/(?P<pk>\d+)/$', show_experiment_configuration, name='show_experiment_configuration'),
    url(r'^configuration/(?P<pk>\d+)/edit', edit_experiment_configuration, name='edit_experiment_configuration'),
    url(r'^api/configuration/(?P<pk>\d+)/delete', delete_experiment_configuration,
        name='delete_experiment_configuration'),
    url(r'^api/configuration/round/(?P<pk>\-?\d+)$', update_round_configuration, name='update_round_configuration'),
    url(r'^api/configuration/round/param/(?P<pk>\-?\d+)$', update_round_param_value, name='update_round_param_value'),
    url(r'^api/configuration/experiment/(?P<pk>\-?\d+)$', update_experiment_configuration,
        name='update_experiment_configuration'),
    url(r'^api/configuration/experiment/param/(?P<pk>\-?\d+)$', update_experiment_param_value,
        name='update_experiment_param_value'),
    url(r'^experimenter/bookmark-experiment-metadata$', toggle_bookmark_experiment_metadata,
        name='bookmark_experiment_metadata'),
    url(r'^api/configuration/clone', clone_experiment_configuration, name='clone_experiment_configuration'),
    url(r'^api/experiment/participant-ready$', participant_ready, name='participant_ready'),
    url(r'^api/experiment/(?P<pk>\d+)/check-ready-participants$', check_ready_participants,
        name='check_ready_participants'),
    url(r'^api/experiment/(?P<pk>\d+)/chat$', handle_chat_message, name='handle_chat_message'),
    url(r'^api/experiment/clone', clone_experiment, name='clone_experiment'),
    url(r'^api/experiment/create', create_experiment, name='create_experiment'),
    url(r'^api/experiment/update', update_experiment, name='update_experiment'),
    url(r'^api/experimenter/save-notes', save_experimenter_notes, name='save_experimenter_notes'),
    url(r'^api/experimenter/round-data', get_round_data, name='get_round_data'),
    url(r'^api/dashboard', get_dashboard_view_model, name='dashboard_view_model'),
    url(r'bug-report', RedirectView.as_view(url='https://github.com/virtualcommons/vcweb/issues/new'),
        name='report_issues'),
    url(r'^autocomplete/participant-institution/$', views.InstitutionAutocomplete.as_view(),
        name='institution-autocomplete'),
    url(r'^autocomplete/participant-major/$', views.ParticipantMajorAutocomplete.as_view(),
        name='major-autocomplete'),
    # url(r'bug-report', BugReportFormView.as_view(), name='report_issues'),
    # match arbitrary experiment URL prefix fragments for logging / login /
    # logout / accessing the dashboard view model
    # url(r'api/log/(?P<participant_group_id>\d+)$', api_logger, name='api_logger'),
    # url(r'api/login', participant_api_login, name='participant_api_login'),
    # url(r'api/logout', api_logout, name='api_logout'),
    url(r'^contact/$', views.AntiSpamContactFormView.as_view(), name='contact_form'),
]

router = routers.DefaultRouter(trailing_slash=False)
router.register(r'experiments', views.ManageExperimentViewSet, basename='experiment')

vcweb/urls.py
from cas import views as cas_views

from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='index.html'), name='about'),
    url(r'^contact/sent/$', TemplateView.as_view(template_name='contact_form/contact_form_sent.html'),
        name='contact_form_sent'),
    url(r'^invalid-request$', TemplateView.as_view(template_name='invalid_request.html'),
        name='invalid_request'),
    url(r'^accounts/password/reset/$', auth_views.password_reset,
        {'template_name': 'accounts/password_reset_form.html',
         'password_reset_form': PasswordResetForm}, name='password_reset'),
    url(r'^accounts/password/reset/done/$', auth_views.password_reset_done,
        {'template_name': 'accounts/password_reset_done.html'}, name='password_reset_done'),
    url(r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        name='password_reset_confirm'),
    url(r'^accounts/password/reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),

    # FIXME: ideally this should be set up dynamically by iterating through each
    # ExperimentMetadata instance and using their namespace (e.g., replace all
    # instances of forestry with ExperimentMetadata.namespace)
    #    url(r'^forestry/', include('vcweb.experiment.forestry.urls', namespace='forestry', app_name='forestry')),
    #    url(r'^bound/', include('vcweb.experiment.bound.urls', namespace='bound', app_name='bound')),
    #    url(r'^lighterprints/', include('vcweb.experiment.lighterprints.urls', namespace='lighterprints',
    #                                    app_name='lighterprints')),
    #    url(r'^broker/', include('vcweb.experiment.broker.urls', namespace='broker', app_name='broker')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cas/login', cas_views.login, name='cas_login'),
    url(r'^cas/logout', cas_views.logout, name='cas_logout'),
    url(r'^cas/error', TemplateView.as_view(template_name='cas_access_forbidden.html'), name='cas_error'),
    # subject pool urls
    url(r'^subject-pool/', include('vcweb.core.subjectpool.urls',
                                   app_name='subjectpool', namespace='subjectpool')),
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
]


def experiment_urls():
    for experiment in settings.VCWEB_EXPERIMENTS:
        experiment_name = experiment.rpartition('.')[2]
# include all experiment urls.py under the experiment name's namespace
        yield url(r'^' + experiment_name + '/',
                  include(experiment + '.urls', namespace=experiment_name, app_name=experiment_name))

urlpatterns += experiment_urls()
# core urls catches everything else
urlpatterns.append(
    url(r'', include('vcweb.core.urls', namespace='core', app_name='core')))


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += [
        url(r'^500/$', TemplateView.as_view(template_name='500.html')),
        url(r'^404/$', TemplateView.as_view(template_name='404.html')),
        url(r'^403/$', TemplateView.as_view(template_name='403.html')),
    ]
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

vcweb/core/subjectpool/models.py
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import get_template
from django.utils import timezone
from vcweb.core.models import ExperimentSession, ParticipantSignup

class InvitationEmail(object):

    def __init__(self, request):
        self.request = request
        self.plaintext_template = get_template('subjectpool/email/invitation-email.txt')

    @property
    def site_url(self):
        site = get_current_site(self.request)
        if self.request.is_secure():
            return "https://" + site.domain
        else:
            return "http://" + site.domain

    def get_plaintext_content(self, message, session_ids):
        return self.plaintext_template.render({
            'SITE_URL': self.site_url,
            'invitation_text': message,
            'session_list': ExperimentSession.objects.filter(pk__in=session_ids),
        })


def generate_participant_report(writer=None, experiment_metadata=None, **kwargs):
    if writer is None or experiment_metadata is None:
        raise ValueError("Please enter in a valid writable thing and an experiment metadata")
    writer.writerow(["Participant List for {0}".format(experiment_metadata.title), experiment_metadata.namespace,
                     "Generated on {0}".format(timezone.now())])
    writer.writerow(['Email', 'Name', 'Username', 'Class Status', 'Attendance', 'Experiment Session Location',
                     'Experiment Session Start Time', 'Experiment Session End Time', 'Experiment Session Capacity',
                     'Experiment Session Creator', ])
    for ps in ParticipantSignup.objects.with_experiment_metadata(experiment_metadata=experiment_metadata, **kwargs):
        invitation = ps.invitation
        participant = invitation.participant
        experiment_session = invitation.experiment_session
        writer.writerow([participant.email, participant.full_name, participant.username, participant.class_status,
                         ps.get_attendance_display(),
                         experiment_session.location,
                         experiment_session.scheduled_date,
                         experiment_session.scheduled_end_date,
                         experiment_session.capacity,
                         experiment_session.creator
                         ])

vcweb/core/subjectpool/forms.py
import logging


from django import forms
from django.forms import widgets, CheckboxInput, ModelForm
from django.utils.translation import ugettext_lazy as _
from dal import autocomplete

from vcweb.core.forms import NumberInput
from vcweb.core.models import (ParticipantSignup, ExperimentSession, Institution)


logger = logging.getLogger(__name__)

HOUR_CHOICES = [(i, i) for i in range(0, 23)]
MIN_CHOICES = [(i, i) for i in (0, 15, 30, 45)]


class CancelSignupForm(forms.Form):
    pk = forms.IntegerField()

    def clean_pk(self):
        data = self.cleaned_data['pk']
        try:
            self.signup = ParticipantSignup.objects.select_related('invitation__experiment_session',
                                                                   'invitation__participant').get(pk=data)
        except ParticipantSignup.DoesNotExist:
            raise forms.ValidationError(_("No signup found with pk %s" % data))
        return data


class ExperimentSessionForm(forms.ModelForm):
    def __init__(self, post_dict=None, instance=None, pk=None, user=None, **kwargs):
        if instance is None and pk is not None and pk != '-1':
            instance = ExperimentSession.objects.get(pk=pk)
        super(ExperimentSessionForm, self).__init__(post_dict, instance=instance, **kwargs)
        self.user = user
        if post_dict:
            self.request_type = post_dict.get('request_type')

    def save(self, commit=True):
        es = super(ExperimentSessionForm, self).save(commit=False)
        if self.request_type == 'delete':
            logger.warn("Deleting experiment session %s", es)
            es.delete()
        else:
            es.creator = self.user
            if commit:
                es.save()
        return es

    class Meta:
        model = ExperimentSession
        exclude = ('creator', 'date_created', 'invitation_text')


class SessionInviteForm(forms.Form):
    GENDER_CHOICES = (('A', 'All'), ('M', 'Male'), ('F', 'Female'),)

    number_of_people = forms.IntegerField(
        help_text=_("Number of participants to invite to the selected experiment session(s)"),
        widget=NumberInput(attrs={'value': 0, 'class': 'input-mini'}))
    only_undergrad = forms.BooleanField(
        help_text=_("Limit to self-reported undergraduate students"),
        widget=CheckboxInput(attrs={'checked': True}), required=False)
    port_of_mars = forms.BooleanField(
        help_text=_("Limit to Port of Mars Signups"),
        required=False
    )
    gender = forms.ChoiceField(choices=GENDER_CHOICES)
    affiliated_institution = forms.ModelChoiceField(
        queryset=Institution.objects.all(),
        required=False,
        initial=1,
        widget=autocomplete.ModelSelect2(
            url='core:institution-autocomplete',
            attrs={
                'data-placeholder': 'Institution name',
                'data-minimum-input-length': 3,
            }
        )
    )
    invitation_subject = forms.CharField(widget=widgets.TextInput())
    invitation_text = forms.CharField(widget=widgets.Textarea(attrs={'rows': '4'}))


class ParticipantAttendanceForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(ParticipantAttendanceForm, self).__init__(*args, **kwargs)
        self.fields['attendance'].widget.attrs['class'] = 'form-control input-sm'

    class Meta:
        model = ParticipantSignup
        fields = ['attendance']

vcweb/core/templates/accounts/asu_registration.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block title %}ASU Experiment Registration{% endblock %}
{% block page %}
<div id="error-messages"></div>
<div class='panel panel-default'>
    <div class='panel-heading'>
        <h3 class='panel-title'>vcweb email distribution list signup for {{ request.user.get_full_name }}</h3>
    </div>
    <div class='panel-body'>
        Please fill out all of the following fields to be registered with our experiment mailing list. In order to
        participate in our experiments you <b>must be an undergraduate student currently enrolled at ASU and at
        least 18 years of age</b>. If you have any further questions, please see <a href='/ostromlab/faq'>our FAQ</a> or
    <a href='/contact'>send us a message</a>.
    </div>
</div>
<form id='vcweb-form' method='post' class='form-horizontal' action='/cas/asu/submit/'>
    {% csrf_token %}
    {%  bootstrap_form form layout="horizontal" %}
    <div class="form-group">
        <div class="col-md-offset-3 col-md-9">
            <button type='submit' id='submitForm' class='btn btn-primary'>Save</button>
        </div>
    </div>
</form>
{% endblock page %}

{% block javascript %}
    {{ form.media }}
    {% include "includes/jquery.validate.html" %}
    {{  block.super }}
    <script type='text/javascript'>
    $(document).ready(function() {
        $("#vcweb-form :input:visible:enabled:first").focus();
        $('#vcweb-form').validate({
                rules: {
                    gender: {
                        required: true
                    },
                    class_status: {
                        required: true
                    },
                    favorite_sport: {
                        required: true
                    },
                    favorite_color: {
                        required: true
                    },
                    favorite_food: {
                        required: true
                    },
                    favorite_movie_genre: {
                        required:true
                    },
                    email: {
                        required: true,
                        email: true,
                        remote: {
                            url: "/accounts/check-email",
                            type: "get",
                            data: {
                                email: function() {
                                    return $( "#id_email" ).val();
                                }
                            }
                        }
                    }
                },
                messages: {
                    class_status: "Please enter your class status",
                    gender: "Please enter your gender",
                    email: {
                        remote: 'This email is already registered in our system. <a href="https://vcweb.asu.edu/accounts/password/reset">Request a new password?</a>'
                    }
                },
            });
    });
</script>
{%  endblock javascript %}

vcweb/core/templates/accounts/login.html
{% extends "forms/base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block title %}Virtual Commons Web Login{% endblock %}
{% block page %}
<div class="row">
    <div class="col-md-6">
        <h3>Returning User</h3>
        <p>If you've forgotten your password, you can <a href='{% url "password_reset" %}'>request a new one</a>.</p>
        <form id='vcweb-form' role="form" class="form-horizontal" method="post">
            {% csrf_token %}
            {%  bootstrap_form form layout="horizontal" field_class="col-md-6"%}
            {% buttons layout='horizontal'%}
                <button type="submit" class="btn btn-primary">
                    <i class='fa fa-user'></i> Sign In
                </button>
            {% endbuttons %}
        </form>
    </div>
    <div class="col-md-6">
        <div class="cas-login">
            <p><img src="{% static 'images/ASU/ASU_logo.jpg' %}" alt="ASU Logo" width="50%"></p>
            <p>
            <a class='external' target='_blank' href='https://getprotected.asu.edu/services/auth'>CAS authentication</a> for ASU students
            </p>
            <div id="login_submit">
                <a href="{% url 'cas_login' %}" class='submit'>Sign In</a>
            </div>
        </div>
    </div>
</div>
{% endblock page %}

vcweb/core/templates/accounts/password_reset_done.html
{% extends "base.html" %}

{% block title %}VCWEB Password Reset Complete{% endblock %}

{% block page %}
<h3>Reminder sent</h3>
<p>
We've sent you an email with instructions on resetting your password.  Please <a href='/contact'>let us know</a> if you
don't receive the email or encounter other problems.
</p>

{% endblock %}

vcweb/core/templates/accounts/password_reset_form.html
{% extends "forms/base.html" %}
{% block title %}Password Reset{% endblock %}
{% block form-title %}
<h3>Reset your password</h3>
<p>
    Please enter your email address below and we'll send you instructions for setting a new password.
</p>
{% endblock form-title %}
{% block form %}
{% include "includes/bootstrap-form.html" %}
    <div class="form-group">
    <div class="col-md-offset-3 col-md-9">
      <button type='submit' class='btn btn-primary'>Submit</button>
    </div>
  </div>
{% endblock %}

{% block javascript %}
{{block.super}}
<script src='//cdnjs.cloudflare.com/ajax/libs/jquery-url-parser/2.3.1/purl.min.js'></script>
<script>
$(function() {
    var url = $.url();
    var email = $.url().param('email');
    if (email) {
        $('#id_email').val(email);
    }
});
</script>

{% endblock %}

vcweb/core/templates/accounts/port_of_mars_registration_form.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block title %}Port Of Mars ASU Student Registration{% endblock %}
{% block page %}
<div id="error-messages"></div>
<div class='panel panel-default'>
    <div class='panel-heading'>
        <h3 class='panel-title'>Please fill in the following fields</h3>
    </div>
    <div class='panel-body'>
        Please fill out all of the following fields to be registered with the Port of Mars experiment mailing list. In
        order to participate in this experiment you <b>must be an undergraduate student currently enrolled at ASU and at
            least 18 years of age</b>. If you have any further questions, please see <a href='/ostromlab/faq'>our FAQ</a> or
        <a href='/contact'>send us a message</a>.
    </div>
</div>
<form id='vcweb-form' method='post' class='form-horizontal'>
    {% csrf_token %}
    {%  bootstrap_form form layout="horizontal" %}
    <div class="form-group">
        <div class="col-md-offset-3 col-md-10">
            <button type='submit' id='submitForm' class='btn btn-primary'>Register</button>
        </div>
    </div>
</form>
{% endblock page %}

vcweb/core/templates/accounts/profile.html
{% extends "forms/base.html" %}

{% load static %}

{% block title %}Your Account{% endblock %}

{% block form-title %}
    <h3>{{ request.user.get_full_name }}</h3>
    <div id="error-messages"></div>
{% endblock form-title %}

{% block form %}
{% include "includes/bootstrap-form.html" %}
    <div class="form-group">
    <div class="col-md-offset-3 col-md-9">
        <button type='submit' id='submitForm' class='btn btn-primary'>Save</button>
    </div>
  </div>
{% endblock %}

{% block javascript %}
    {{  block.super }}
    {{ form.media }}
        <script type='text/javascript'>
        $(document).ready(function() {
            $("#vcweb-form :input:visible:enabled:first").focus();

            $('#vcweb-form').validate({
                rules: {
                    major: {
                        required: "#id_can_receive_invitations:checked"
                    },
                    class_status: {
                        required: "#id_can_receive_invitations:checked"
                    },
                    gender: {
                        required: "#id_can_receive_invitations:checked"
                    },
                    email: {
                        required: true,
                        email: true,
                        remote: {
                            url: "/accounts/check-email",
                            type: "get",
                            data: {
                                email: function() {
                                    return $( "#id_email" ).val();
                                }
                            }
                        }
                    }
                },
                messages: {
                    class_status: "Please enter your class status",
                    gender: "Please enter your gender",
                    email: {
                        remote: 'This email is already registered in our system. <a href="https://commons.asu.edu/accounts/password/reset">Request a new password?</a>'
                    }
                },
                submitHandler: function(form) {
                    var formData = $('#vcweb-form').serialize();
                    console.debug("submitting form");
                    $.post("/accounts/profile/update", formData,
                         function(data) {
                            if (data.success) {
                                $("#error-messages").html('<div class="alert alert-success">Your profile has been updated. Thank you for registering!</strong></div>');
                            } else {
                                $("#error-messages").html('<div class="alert alert-danger"><strong>'+data.message+'</strong></div>');
                            }
                        });

                }
            });
        });
    </script>
    {%  endblock javascript %}

vcweb/core/templates/accounts/register.html
{% extends "forms/base.html" %}

{% block title %}VCWEB Account Registration{% endblock %}

{% block form-title %}
    <h3>New User</h3>
    <p>
        Already have an account?  You can <a href='{% url "core:login" %}'>login here</a> or <a href='{% url "password_reset" %}'>retrieve your password</a>.
    </p>
{% endblock form-title%}

{% block form %}
    {% include "includes/bootstrap-form.html" %}
    <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
          <button type='submit' class='btn btn-primary'>Submit</button>
    </div>
  </div>
{% endblock form %}

{% block javascript %}
    {{ block.super }}
    <script type='text/javascript'>
    $(document).ready(function() {
        $("#vcweb-form :input:visible:enabled:first").focus();
        console.debug("about to validate form");
        $('#vcweb-form').validate();
        $('#id_password').rules("add", {
            minlength: 3
        });
        $('#id_confirm_password').rules("add", {
            equalTo: "#id_password",
            minlength: 3,
            messages: {
                equalTo: "Please make sure your passwords match."
            }
        });
    });
    </script>
{% endblock %}

vcweb/core/templates/accounts/registration_complete.html
{% extends "forms/base.html" %}

{% block title %}Virtual Commons Web Registration{% endblock %}

{% block head %}
{{ block.super }}

<script type='text/javascript'>
$(document).ready(function() {
    $(':input').addClass('required');
    $('#registrationForm').validate();
    $('#id_email').focus();
});
</script>

{% endblock head %}

{% block content %}

<p>
Thanks for registering.  An email has been sent to you with further instructions on how to activate your account.   
After activating your account, you will be able to login.
</p>

{% endblock content %}

vcweb/core/templates/accounts/unsubscribe.html
{% extends "base.html" %}

{% block title %} Experiment Invitation Unsubscription {% endblock %}

{% block page %}
    <div>
    {% if successfully_unsubscribed %}
        <h2>Unsubscribe Successful</h2>
        <p>
            You will no longer receive invitations for experiments. If you continue receiving invitations please
            contact us at <a href='mailto:ostromlab@asu.edu'>ostromlab@asu.edu</a>.
        </p>
        <p>
        If you'd like to resubscribe visit your <a href='//acounts/profile'>account profile</a> and check the <b>can receive invitations</b> checkbox.
        </p>
    {% else %}
        <h2>Unsubscribe</h2>
        <p>To stop receiving email invitations to our experiments please confirm by clicking on the button below.</p>
        <form action={% url 'core:unsubscribe' %} method="POST">
            {% csrf_token %}
            <button class="btn btn-primary" type="submit">Unsubscribe</button>
        </form>
    {% endif %}
    </div>
{% endblock page %}