vcweb/core/subjectpool/urls.py
from django.conf.urls import url

from .views import (subjectpool_index, manage_experiment_session, get_session_events, manage_participant_attendance,
                    send_invitations, get_invitations_count, invite_email_preview, experiment_session_signup,
                    submit_experiment_session_signup, cancel_experiment_session_signup, download_experiment_session,
                    add_participant)

urlpatterns = [
    url(r'^$', subjectpool_index, name='subjectpool_index'),
    url(r'^session/manage/(?P<pk>\-?\d+)$', manage_experiment_session, name='manage_experiment_session'),
    url(r'^session/detail/event/(?P<pk>\d+)$', manage_participant_attendance, name='session_event_detail'),
    url(r'^session/(?P<pk>\d+)/participant/add/$', add_participant, name='add_participant'),
    url(r'^session/invite$', send_invitations, name='send_invites'),
    url(r'^session/invite/count$', get_invitations_count, name='get_invitations_count'),
    url(r'^session/email-preview$', invite_email_preview, name='invite_email_preview'),
    url(r'^session/(?P<pk>\d+)/download/$', download_experiment_session, name='download_experiment_session'),
    url(r'^session/events$', get_session_events, name='session_events'),

    url(r'^signup/$', experiment_session_signup, name='experiment_session_signup'),
    url(r'^signup/submit/$', submit_experiment_session_signup, name='submit_experiment_session_signup'),
    url(r'^signup/cancel/$', cancel_experiment_session_signup, name='cancel_experiment_session_signup'),
]

vcweb/urls.py
from cas import views as cas_views

from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='index.html'), name='about'),
    url(r'^contact/sent/$', TemplateView.as_view(template_name='contact_form/contact_form_sent.html'),
        name='contact_form_sent'),
    url(r'^invalid-request$', TemplateView.as_view(template_name='invalid_request.html'),
        name='invalid_request'),
    url(r'^accounts/password/reset/$', auth_views.password_reset,
        {'template_name': 'accounts/password_reset_form.html',
         'password_reset_form': PasswordResetForm}, name='password_reset'),
    url(r'^accounts/password/reset/done/$', auth_views.password_reset_done,
        {'template_name': 'accounts/password_reset_done.html'}, name='password_reset_done'),
    url(r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        name='password_reset_confirm'),
    url(r'^accounts/password/reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),

    # FIXME: ideally this should be set up dynamically by iterating through each
    # ExperimentMetadata instance and using their namespace (e.g., replace all
    # instances of forestry with ExperimentMetadata.namespace)
    #    url(r'^forestry/', include('vcweb.experiment.forestry.urls', namespace='forestry', app_name='forestry')),
    #    url(r'^bound/', include('vcweb.experiment.bound.urls', namespace='bound', app_name='bound')),
    #    url(r'^lighterprints/', include('vcweb.experiment.lighterprints.urls', namespace='lighterprints',
    #                                    app_name='lighterprints')),
    #    url(r'^broker/', include('vcweb.experiment.broker.urls', namespace='broker', app_name='broker')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cas/login', cas_views.login, name='cas_login'),
    url(r'^cas/logout', cas_views.logout, name='cas_logout'),
    url(r'^cas/error', TemplateView.as_view(template_name='cas_access_forbidden.html'), name='cas_error'),
    # subject pool urls
    url(r'^subject-pool/', include('vcweb.core.subjectpool.urls',
                                   app_name='subjectpool', namespace='subjectpool')),
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
]


def experiment_urls():
    for experiment in settings.VCWEB_EXPERIMENTS:
        experiment_name = experiment.rpartition('.')[2]
# include all experiment urls.py under the experiment name's namespace
        yield url(r'^' + experiment_name + '/',
                  include(experiment + '.urls', namespace=experiment_name, app_name=experiment_name))

urlpatterns += experiment_urls()
# core urls catches everything else
urlpatterns.append(
    url(r'', include('vcweb.core.urls', namespace='core', app_name='core')))


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += [
        url(r'^500/$', TemplateView.as_view(template_name='500.html')),
        url(r'^404/$', TemplateView.as_view(template_name='404.html')),
        url(r'^403/$', TemplateView.as_view(template_name='403.html')),
    ]
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

vcweb/core/subjectpool/models.py
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import get_template
from django.utils import timezone
from vcweb.core.models import ExperimentSession, ParticipantSignup

class InvitationEmail(object):

    def __init__(self, request):
        self.request = request
        self.plaintext_template = get_template('subjectpool/email/invitation-email.txt')

    @property
    def site_url(self):
        site = get_current_site(self.request)
        if self.request.is_secure():
            return "https://" + site.domain
        else:
            return "http://" + site.domain

    def get_plaintext_content(self, message, session_ids):
        return self.plaintext_template.render({
            'SITE_URL': self.site_url,
            'invitation_text': message,
            'session_list': ExperimentSession.objects.filter(pk__in=session_ids),
        })


def generate_participant_report(writer=None, experiment_metadata=None, **kwargs):
    if writer is None or experiment_metadata is None:
        raise ValueError("Please enter in a valid writable thing and an experiment metadata")
    writer.writerow(["Participant List for {0}".format(experiment_metadata.title), experiment_metadata.namespace,
                     "Generated on {0}".format(timezone.now())])
    writer.writerow(['Email', 'Name', 'Username', 'Class Status', 'Attendance', 'Experiment Session Location',
                     'Experiment Session Start Time', 'Experiment Session End Time', 'Experiment Session Capacity',
                     'Experiment Session Creator', ])
    for ps in ParticipantSignup.objects.with_experiment_metadata(experiment_metadata=experiment_metadata, **kwargs):
        invitation = ps.invitation
        participant = invitation.participant
        experiment_session = invitation.experiment_session
        writer.writerow([participant.email, participant.full_name, participant.username, participant.class_status,
                         ps.get_attendance_display(),
                         experiment_session.location,
                         experiment_session.scheduled_date,
                         experiment_session.scheduled_end_date,
                         experiment_session.capacity,
                         experiment_session.creator
                         ])

vcweb/core/subjectpool/views.py
from django.conf import settings
from django.contrib import messages
from django.core.mail import EmailMultiAlternatives
from django.db import transaction
from django.forms.models import modelformset_factory
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.http import require_GET, require_POST

from vcweb.core.decorators import group_required, ownership_required
from vcweb.core.http import JsonResponse, dumps
from vcweb.core.models import (Participant, ParticipantSignup, PermissionGroup, ExperimentSession, ExperimentMetadata,
                               Invitation, send_markdown_email)
from vcweb.core.views import mimetypes

from .forms import (SessionInviteForm, ExperimentSessionForm, ParticipantAttendanceForm, CancelSignupForm)
from .models import InvitationEmail, generate_participant_report

from datetime import datetime
from time import mktime

import logging
import random
import unicodecsv
import markdown

logger = logging.getLogger(__name__)


@group_required(PermissionGroup.experimenter)
@require_GET
def subjectpool_index(request):
    """
    Provides subject recruitment interface with all the active and past experiment sessions.
    """
    experimenter = request.user.experimenter
    es_list = ExperimentSession.objects.select_related('experiment_metadata').filter(creator=request.user)
    session_list = [session.to_dict() for session in es_list]
    experiment_metadata_list = [em.to_dict() for em in ExperimentMetadata.objects.bookmarked(experimenter)]
    potential_participants_count = Participant.objects.active().count()
    data = {
        'session_list': session_list,
        'experiment_metadata_list': experiment_metadata_list,
        'allEligibleParticipants': potential_participants_count,
        'potentialParticipantsCount': potential_participants_count,
    }
    return render(request, "subjectpool/index.html",
                  {"view_model_json": dumps(data), "form": SessionInviteForm()})


@group_required(PermissionGroup.experimenter)
@require_POST
@transaction.atomic
def manage_experiment_session(request, pk):
    form = ExperimentSessionForm(request.POST or None, pk=pk, user=request.user)
    if form.is_valid():
        es = form.save()
        return JsonResponse({'success': True, 'session': es})
    return JsonResponse({'success': False, 'errors': form.errors})


@group_required(PermissionGroup.experimenter)
@require_GET
def get_session_events(request):
    """
    Returns the list of Experiment sessions that fall within the given range,
    Used by the subject pool calendar to display experiment sessions falling within the date range shown
    """
    from_date = request.GET.get('from', None)
    to_date = request.GET.get('to', None)
    criteria = dict()
    if to_date:
        criteria.update(scheduled_end_date__gte=timestamp_to_datetime(from_date))

    queryset = ExperimentSession.objects.select_related('experiment_metadata').filter(**criteria)
    objects_body = []
    for event in queryset:
        index = event.pk % 20  # for color selection
        field = {
            "id": event.pk,
            "title": event.experiment_metadata.title,
            "url": "session/detail/event/" + str(event.pk),
            "class": "event-color-" + str(index),
            "start": datetime_to_timestamp(event.scheduled_date),
            "end": datetime_to_timestamp(event.scheduled_end_date),
            "capacity": event.capacity
        }
        objects_body.append(field)

    objects_head = {"success": True, "result": objects_body}

    return JsonResponse(objects_head)


def timestamp_to_datetime(timestamp):
    """
    Converts string timestamp to python datetime object with json fix
    """
    if isinstance(timestamp, str):

        if len(timestamp) == 13:
            timestamp = int(timestamp) / 1000

        return datetime.fromtimestamp(timestamp)
    else:
        return ""


def datetime_to_timestamp(date):
    """
    Converts python datetime object to timestamp with json fix
    """
    if isinstance(date, datetime):

        timestamp = mktime(date.timetuple())
        json_timestamp = int(timestamp) * 1000

        return '{0}'.format(json_timestamp)
    else:
        return ""


@group_required(PermissionGroup.experimenter)
@require_POST
def get_invitations_count(request):
    """
    API endpoint that returns the potential participant count based on the selected experiment metadata and Institution
    """
    form = SessionInviteForm(request.POST or None)
    if form.is_valid():
        session_pk_list = request.POST.get('session_pk_list').split(",")
        experiment_metadata_ids = ExperimentSession.objects.filter(pk__in=session_pk_list).values_list(
            'experiment_metadata__pk', flat=True)
        if len(set(experiment_metadata_ids)) == 1:
            # only allow invitations for sessions of a single ExperimentMetadata type
            # get the experiment metadata pk of any session (This is ensured as it is a constraint)
            potential_participants = Participant.objects.invitation_eligible(
                experiment_metadata_ids[0],
                gender=form.cleaned_data.get('gender'),
                institution=form.cleaned_data.get('affiliated_institution'),
                port_of_mars=form.cleaned_data.get('port_of_mars'),
                only_undergrad=form.cleaned_data.get('only_undergrad'))
            return JsonResponse({'success': True, 'invitesCount': len(potential_participants)})
    return JsonResponse({'success': False, 'invitesCount': 0, 'errors': form.errors})


@group_required(PermissionGroup.experimenter)
@require_POST
def send_invitations(request):
    """
    Sends out invitation emails to random participants which match the required invitation criteria,
    using the provided email subject and message. Also returns the total number of invites sent.
    """
    user = request.user
    form = SessionInviteForm(request.POST or None)

    if form.is_valid():
        invitation_subject = form.cleaned_data.get('invitation_subject')
        invitation_text = form.cleaned_data.get('invitation_text')
        # use currently logged in experimenter as the sender of the
        # invitations.
        from_email = user.email

        session_pk_list = request.POST.get('session_pk_list').split(",")
        invitation_count = form.cleaned_data.get('number_of_people')
        affiliated_institution = form.cleaned_data.get('affiliated_institution')

        experiment_sessions = ExperimentSession.objects.filter(pk__in=session_pk_list)
        experiment_metadata_pk_list = experiment_sessions.values_list('experiment_metadata__pk', flat=True)

        if len(set(experiment_metadata_pk_list)) == 1:
            # get the experiment metadata pk of any session, as all sessions selected by experimenter to send
            # invitations belong to same experiment metadata (This has to be ensured as it is a constraint)
            experiment_metadata_pk = experiment_metadata_pk_list[0]

            potential_participants = list(Participant.objects.invitation_eligible(
                experiment_metadata_pk,
                institution=affiliated_institution,
                only_undergrad=form.cleaned_data.get('only_undergrad'),
                gender=form.cleaned_data.get('gender')))
            potential_participants_count = len(potential_participants)

            final_participants = None

            if potential_participants_count == 0:
                final_participants = []
                message = "There are no more eligible participants that can be invited for this experiment."
            else:
                if potential_participants_count < invitation_count:
                    # less candidate participants than the number of requested
                    # participants, use them all
                    final_participants = potential_participants
                else:
                    final_participants = random.sample(potential_participants, invitation_count)
                message = "Invitations were sent to %s / %s participants." % (len(final_participants), invitation_count)

                today = timezone.now()
                invitations = []
                recipient_list = [settings.DEFAULT_FROM_EMAIL]
                for participant in final_participants:
                    recipient_list.append(participant.email)
                    invitations.extend([Invitation(participant=participant,
                                                   experiment_session=es,
                                                   date_created=today,
                                                   sender=user)
                                        for es in experiment_sessions])
                Invitation.objects.bulk_create(invitations)

                if settings.ENVIRONMENT.is_production:
                    ie = InvitationEmail(request)
                    plaintext_content = ie.get_plaintext_content(invitation_text, session_pk_list)
                    html_content = markdown.markdown(plaintext_content)
                    msg = EmailMultiAlternatives(subject=invitation_subject, body=plaintext_content,
                                                 from_email=from_email, to=[from_email], bcc=recipient_list)
                    msg.attach_alternative(html_content, "text/html")
                    msg.send()
                else:
                    logger.debug("Sending invitation emails in non-production environment is disabled: %s",
                                 recipient_list)
            return JsonResponse({'success': True, 'message': message, 'invitesCount': len(final_participants)})
        else:
            return JsonResponse({
                'success': False,

vcweb/core/subjectpool/templates/subjectpool/experiment-session-detail.html
{% extends "experimenter/base.html" %}
{% block head %}
{{ block.super }}
<link rel='stylesheet' href='//cdn.datatables.net/1.10.11/css/jquery.dataTables.min.css'>
{% endblock %}
{% block title %}
    Experiment Session Detail
{% endblock %}
{% block page %}
    <div id='page'>
        <a class="btn btn-default" href="{% url 'subjectpool:subjectpool_index' %}"><i class="fa fa-arrow-left"></i> Back</a>
        <div id="session-detail" class="callout callout-info">
            <p><strong>Experiment: </strong>
            {{ session.experiment_metadata.title }}
            <p><strong>Date/Time: </strong> {{ session.scheduled_date.date }}, {{ session.scheduled_date.time }} -
            {% if session.scheduled_end_date.date != session.scheduled_date.date %}
            {{ session.scheduled_end_date.date }},
            {% endif %}
            {{ session.scheduled_end_date.time }}</p>
            <p><strong>Location: </strong> {{ session.location }}</p>
            <p><strong>Capacity: </strong> {{ session.capacity }}</p>
            <p><strong>Waitlist enabled: </strong> {{ session.waitlist }}</p>
            {% if formset.forms|length > 0 %}
            <a target="_blank" href="/subject-pool/session/{{ session.pk }}/download/">
               <i class='fa fa-table'></i> Download registered participant list (CSV)
            </a>
            {% endif %}
        </div>
        <div class="alert alert-warning">
            <form class="form-horizontal">
                <div class="form-group">
                    <label class='control-label col-sm-4' for="bulkAction">Mark all participants' attendance as</label>
                    <div class='col-sm-6'>
                        <select id="bulkAction" name="bulkAction" class="form-control input-sm">
                            <option value="-1">Select an option</option>
                            <option value="0">participated</option>
                            <option value="1">turned away</option>
                            <option value="2">absent</option>
                            <option value="3">signed up</option>
                            <option value="4">waitlisted</option>
                        </select>
                    </div>
                </div>
                <div class='form-group'>
                    <div class='col-sm-offset-4 col-sm-6'>
                        <b><i class='fa fa-exclamation-triangle'></i> Note:</b> This does not save any changes, click on the save button below to apply these changes.
                    </div>
                </div>
            </form>
            {# FIXME: replace with KO #}
            <div class='alert-danger' id='add-participant-error'></div>
            <form class="form-horizontal" id="addParticipant">
                {% csrf_token %}
                <div class="form-group">
                    <label class='control-label col-sm-4' for="participantEmail">Manually add participant by email</label>
                    <div class='col-sm-6'>
                        <input type="email" id="participantEmail" name="participantEmail" placeholder='participant email' class="form-control input-sm" />
                    </div>
                </div>
                <div class='form-group'>
                    <div class='col-sm-offset-4 col-sm-6'>
                        <button type="submit" class="btn btn-default input-sm">Add Participant</button>
                    </div>
                </div>
            </form>
        </div>
        {% for dict in formset.errors %}
            {% for error in dict.values %}
                <div class="alert alert-error">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        <h3>Registered Participants</h3>
        <form method="POST" id="participant-info" class="form-inline">
            {% csrf_token %}
            {{ formset.management_form }}
            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="participant-table">
                <thead>
                    <tr>
                        <th> First Name </th>
                        <th> Last Name </th>
                        <th> Email </th>
                        <th> Major </th>
                        <th> Class Status </th>
                        <th> Attendance </th>
                    </tr>
                </thead>
                {% for form in formset.forms %}
                {% with form.instance.invitation.participant as participant %}
                <tr>
                    <td>
                        {{ participant.first_name }}
                        {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                        {% endfor %}
                    </td>
                    <td>{{ participant.last_name }}</td>
                    <td>{{ participant.email }}</td>
                    <td>{{ participant.major }}</td>
                    <td>{{ participant.class_status }}</td>
                    {% for field in form.visible_fields %}
                        <td>{{ field }}</td>
                    {% endfor %}
                </tr>
                {% endwith %}
            {% endfor %}
            </table>
            <hr>
            {% if formset.forms|length > 0 %}
            <button type="submit" class="btn btn-success" id="submit-attendance"><i class="fa fa-floppy-o"></i> Save attendance changes</button>
            {% endif %}
        </form>
    </div>
{% endblock %}
{% block javascript %}
    {{ block.super }}
    <script type="text/javascript" src="//cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript">
        $(function() {

            $("#bulkAction").change(function() {
                var optionVal = $(this).val();
                if(optionVal != -1) {
                    $("#participant-table").find("select").val(optionVal);
                }
            });

            $("#addParticipant").submit(function(event) {
                $.post("{% url 'subjectpool:add_participant' session.pk %}", $(event.target).serialize(), function(data) {
                    console.log(data.success);
                    if (data.success) {
                        // reload page to show the added participant
                        location.reload(true);
                    } else {
                        $("#add-participant-error").addClass('alert').text("ERROR: " + data.error);
                    }
                }).fail(function(data) {
                    {# FIXME: replace with KO / react #}
                    if (data.status == 404) {
                        $("#add-participant-error").addClass('alert').html(" <i class='fa fa-exclamation-triangle'></i> Sorry, we couldn't find a participant with that email.");
                    }
                    else {
                        $("#add-participant-error").addClass('alert').html(" <i class='fa fa-exclamation-triangle'></i> ERROR: Something went wrong. Please contact us if this persists.");
                    }
                });
                event.preventDefault();
            });

            oTable = $('#participant-table').dataTable( {
                "sDom": "<'pull-right'f><'clearfix'r>t<'col-md-6'i>",
                "sWrapper": "dataTables_wrapper",
                "paging": false,
            });

            // SEARCH - Add the placeholder for Search and Turn it into in-line formcontrol
            var search_input = $('#participant-table').closest('.dataTables_wrapper').find('div[id$=_filter] input');
            search_input.attr('placeholder', 'name, email, major, or class');
            search_input.addClass('form-control input-sm');
            search_input.css('width', '190px');

            // hack to make sure that the table has all the rows before making post
            // required to make django formset to work
            $("#submit-attendance").click(function() {
                oTable.fnFilter('');
            });
        });
    </script>
{% endblock %}