vcweb/core/subjectpool/urls.py
from django.conf.urls import url

from .views import (subjectpool_index, manage_experiment_session, get_session_events, manage_participant_attendance,
                    send_invitations, get_invitations_count, invite_email_preview, experiment_session_signup,
                    submit_experiment_session_signup, cancel_experiment_session_signup, download_experiment_session,
                    add_participant)

urlpatterns = [
    url(r'^$', subjectpool_index, name='subjectpool_index'),
    url(r'^session/manage/(?P<pk>\-?\d+)$', manage_experiment_session, name='manage_experiment_session'),
    url(r'^session/detail/event/(?P<pk>\d+)$', manage_participant_attendance, name='session_event_detail'),
    url(r'^session/(?P<pk>\d+)/participant/add/$', add_participant, name='add_participant'),
    url(r'^session/invite$', send_invitations, name='send_invites'),
    url(r'^session/invite/count$', get_invitations_count, name='get_invitations_count'),
    url(r'^session/email-preview$', invite_email_preview, name='invite_email_preview'),
    url(r'^session/(?P<pk>\d+)/download/$', download_experiment_session, name='download_experiment_session'),
    url(r'^session/events$', get_session_events, name='session_events'),

    url(r'^signup/$', experiment_session_signup, name='experiment_session_signup'),
    url(r'^signup/submit/$', submit_experiment_session_signup, name='submit_experiment_session_signup'),
    url(r'^signup/cancel/$', cancel_experiment_session_signup, name='cancel_experiment_session_signup'),
]

vcweb/core/urls.py
import logging

from django.conf.urls import url
from django.views.generic import RedirectView, TemplateView
from rest_framework import routers

from . import views
from .api import (get_round_data, save_experimenter_notes, create_experiment, clone_experiment, is_email_available,
                  handle_chat_message, check_ready_participants, participant_ready, )
from .views import (dashboard, LoginView, LogoutView, monitor, RegisterEmailListView, RegisterTestParticipantsView,
                    completed_survey, toggle_bookmark_experiment_metadata, check_survey_completed, ParticipateView,
                    download_data, download_participants, export_configuration, get_dashboard_view_model,
                    update_experiment, update_round_configuration, show_experiment_configuration,
                    edit_experiment_configuration, delete_experiment_configuration, clone_experiment_configuration,
                    unsubscribe, update_round_param_value, update_experiment_param_value,
                    update_experiment_configuration, OstromlabFaqList, cas_asu_registration,
                    cas_asu_registration_submit, account_profile, update_account_profile, update_participants,
                    audit_report)

logger = logging.getLogger(__name__)

'''
URLs for core vcweb app
'''
urlpatterns = [
    url(r'^cas/asu/$', cas_asu_registration, name='cas_asu_registration'),
    url(r'^cas/asu/submit/$', cas_asu_registration_submit, name='cas_asu_registration_submit'),
    url(r'^papers/$', TemplateView.as_view(template_name='papers.html')),
    url(r'^dashboard/$', dashboard, name='dashboard'),
    url(r'^accounts/login/$', LoginView.as_view(), name='login'),
    url(r'^accounts/logout/$', LogoutView.as_view(), name='logout'),
    # url(r'^accounts/add/$', RegistrationView.as_view(), name='register'), # XXX: open registration currently disabled
    url(r'^accounts/profile/$', account_profile, name='profile'),
    url(r'^accounts/mars-signup/$', views.PortOfMarsSignupView.as_view(), name='mars_registration'),
    url(r'^accounts/profile/update$', update_account_profile, name='update_profile'),
    url(r'^accounts/check-email$', is_email_available, name='check_email'),
    url(r'^ostromlab/faq/$', OstromlabFaqList.as_view(), name='ostromlab_faq'),
    url(r'^accounts/unsubscribe$', unsubscribe, name='unsubscribe'),
    url(r'^admin/audit-report$', audit_report, name='audit_report'),
    url(r'^participate/?$', ParticipateView.as_view(), name='participate'),
    url(r'^participate/survey-completed', completed_survey, name='survey_completed'),
    url(r'^participate/(?P<pk>\d+)/check-survey-completed', check_survey_completed, name='check_survey_completed'),
    url(r'^experiment/(?P<pk>\d+)/update-participants$', update_participants, name='update_participant'),
    url(r'^experiment/(?P<pk>\d+)/monitor$', monitor, name='monitor_experiment'),
    url(r'^experiment/(?P<pk>\d+)/register-email-list$', RegisterEmailListView.as_view(), name='register_email_list'),
    url(r'^experiment/(?P<pk>\d+)/register-test-participants$', RegisterTestParticipantsView.as_view(),
        name='register_test_participants'),
    url(r'^experiment/(?P<pk>\d+)/download/(?P<file_type>[\w]+)$', download_data, name='download_data'),
    url(r'^experiment/(?P<pk>\d+)/download-participants/$', download_participants, name='download_participants'),
    url(r'^experiment/(?P<pk>\d+)/export/configuration(?P<file_extension>.[\w]+)$', export_configuration,
        name='export_configuration'),
    url(r'^configuration/(?P<pk>\d+)/$', show_experiment_configuration, name='show_experiment_configuration'),
    url(r'^configuration/(?P<pk>\d+)/edit', edit_experiment_configuration, name='edit_experiment_configuration'),
    url(r'^api/configuration/(?P<pk>\d+)/delete', delete_experiment_configuration,
        name='delete_experiment_configuration'),
    url(r'^api/configuration/round/(?P<pk>\-?\d+)$', update_round_configuration, name='update_round_configuration'),
    url(r'^api/configuration/round/param/(?P<pk>\-?\d+)$', update_round_param_value, name='update_round_param_value'),
    url(r'^api/configuration/experiment/(?P<pk>\-?\d+)$', update_experiment_configuration,
        name='update_experiment_configuration'),
    url(r'^api/configuration/experiment/param/(?P<pk>\-?\d+)$', update_experiment_param_value,
        name='update_experiment_param_value'),
    url(r'^experimenter/bookmark-experiment-metadata$', toggle_bookmark_experiment_metadata,
        name='bookmark_experiment_metadata'),
    url(r'^api/configuration/clone', clone_experiment_configuration, name='clone_experiment_configuration'),
    url(r'^api/experiment/participant-ready$', participant_ready, name='participant_ready'),
    url(r'^api/experiment/(?P<pk>\d+)/check-ready-participants$', check_ready_participants,
        name='check_ready_participants'),
    url(r'^api/experiment/(?P<pk>\d+)/chat$', handle_chat_message, name='handle_chat_message'),
    url(r'^api/experiment/clone', clone_experiment, name='clone_experiment'),
    url(r'^api/experiment/create', create_experiment, name='create_experiment'),
    url(r'^api/experiment/update', update_experiment, name='update_experiment'),
    url(r'^api/experimenter/save-notes', save_experimenter_notes, name='save_experimenter_notes'),
    url(r'^api/experimenter/round-data', get_round_data, name='get_round_data'),
    url(r'^api/dashboard', get_dashboard_view_model, name='dashboard_view_model'),
    url(r'bug-report', RedirectView.as_view(url='https://github.com/virtualcommons/vcweb/issues/new'),
        name='report_issues'),
    url(r'^autocomplete/participant-institution/$', views.InstitutionAutocomplete.as_view(),
        name='institution-autocomplete'),
    url(r'^autocomplete/participant-major/$', views.ParticipantMajorAutocomplete.as_view(),
        name='major-autocomplete'),
    # url(r'bug-report', BugReportFormView.as_view(), name='report_issues'),
    # match arbitrary experiment URL prefix fragments for logging / login /
    # logout / accessing the dashboard view model
    # url(r'api/log/(?P<participant_group_id>\d+)$', api_logger, name='api_logger'),
    # url(r'api/login', participant_api_login, name='participant_api_login'),
    # url(r'api/logout', api_logout, name='api_logout'),
    url(r'^contact/$', views.AntiSpamContactFormView.as_view(), name='contact_form'),
]

router = routers.DefaultRouter(trailing_slash=False)
router.register(r'experiments', views.ManageExperimentViewSet, basename='experiment')

vcweb/urls.py
from cas import views as cas_views

from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='index.html'), name='about'),
    url(r'^contact/sent/$', TemplateView.as_view(template_name='contact_form/contact_form_sent.html'),
        name='contact_form_sent'),
    url(r'^invalid-request$', TemplateView.as_view(template_name='invalid_request.html'),
        name='invalid_request'),
    url(r'^accounts/password/reset/$', auth_views.password_reset,
        {'template_name': 'accounts/password_reset_form.html',
         'password_reset_form': PasswordResetForm}, name='password_reset'),
    url(r'^accounts/password/reset/done/$', auth_views.password_reset_done,
        {'template_name': 'accounts/password_reset_done.html'}, name='password_reset_done'),
    url(r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        name='password_reset_confirm'),
    url(r'^accounts/password/reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),

    # FIXME: ideally this should be set up dynamically by iterating through each
    # ExperimentMetadata instance and using their namespace (e.g., replace all
    # instances of forestry with ExperimentMetadata.namespace)
    #    url(r'^forestry/', include('vcweb.experiment.forestry.urls', namespace='forestry', app_name='forestry')),
    #    url(r'^bound/', include('vcweb.experiment.bound.urls', namespace='bound', app_name='bound')),
    #    url(r'^lighterprints/', include('vcweb.experiment.lighterprints.urls', namespace='lighterprints',
    #                                    app_name='lighterprints')),
    #    url(r'^broker/', include('vcweb.experiment.broker.urls', namespace='broker', app_name='broker')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cas/login', cas_views.login, name='cas_login'),
    url(r'^cas/logout', cas_views.logout, name='cas_logout'),
    url(r'^cas/error', TemplateView.as_view(template_name='cas_access_forbidden.html'), name='cas_error'),
    # subject pool urls
    url(r'^subject-pool/', include('vcweb.core.subjectpool.urls',
                                   app_name='subjectpool', namespace='subjectpool')),
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
]


def experiment_urls():
    for experiment in settings.VCWEB_EXPERIMENTS:
        experiment_name = experiment.rpartition('.')[2]
# include all experiment urls.py under the experiment name's namespace
        yield url(r'^' + experiment_name + '/',
                  include(experiment + '.urls', namespace=experiment_name, app_name=experiment_name))

urlpatterns += experiment_urls()
# core urls catches everything else
urlpatterns.append(
    url(r'', include('vcweb.core.urls', namespace='core', app_name='core')))


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += [
        url(r'^500/$', TemplateView.as_view(template_name='500.html')),
        url(r'^404/$', TemplateView.as_view(template_name='404.html')),
        url(r'^403/$', TemplateView.as_view(template_name='403.html')),
    ]
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

vcweb/core/subjectpool/models.py
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import get_template
from django.utils import timezone
from vcweb.core.models import ExperimentSession, ParticipantSignup

class InvitationEmail(object):

    def __init__(self, request):
        self.request = request
        self.plaintext_template = get_template('subjectpool/email/invitation-email.txt')

    @property
    def site_url(self):
        site = get_current_site(self.request)
        if self.request.is_secure():
            return "https://" + site.domain
        else:
            return "http://" + site.domain

    def get_plaintext_content(self, message, session_ids):
        return self.plaintext_template.render({
            'SITE_URL': self.site_url,
            'invitation_text': message,
            'session_list': ExperimentSession.objects.filter(pk__in=session_ids),
        })


def generate_participant_report(writer=None, experiment_metadata=None, **kwargs):
    if writer is None or experiment_metadata is None:
        raise ValueError("Please enter in a valid writable thing and an experiment metadata")
    writer.writerow(["Participant List for {0}".format(experiment_metadata.title), experiment_metadata.namespace,
                     "Generated on {0}".format(timezone.now())])
    writer.writerow(['Email', 'Name', 'Username', 'Class Status', 'Attendance', 'Experiment Session Location',
                     'Experiment Session Start Time', 'Experiment Session End Time', 'Experiment Session Capacity',
                     'Experiment Session Creator', ])
    for ps in ParticipantSignup.objects.with_experiment_metadata(experiment_metadata=experiment_metadata, **kwargs):
        invitation = ps.invitation
        participant = invitation.participant
        experiment_session = invitation.experiment_session
        writer.writerow([participant.email, participant.full_name, participant.username, participant.class_status,
                         ps.get_attendance_display(),
                         experiment_session.location,
                         experiment_session.scheduled_date,
                         experiment_session.scheduled_end_date,
                         experiment_session.capacity,
                         experiment_session.creator
                         ])

vcweb/core/subjectpool/forms.py
import logging


from django import forms
from django.forms import widgets, CheckboxInput, ModelForm
from django.utils.translation import ugettext_lazy as _
from dal import autocomplete

from vcweb.core.forms import NumberInput
from vcweb.core.models import (ParticipantSignup, ExperimentSession, Institution)


logger = logging.getLogger(__name__)

HOUR_CHOICES = [(i, i) for i in range(0, 23)]
MIN_CHOICES = [(i, i) for i in (0, 15, 30, 45)]


class CancelSignupForm(forms.Form):
    pk = forms.IntegerField()

    def clean_pk(self):
        data = self.cleaned_data['pk']
        try:
            self.signup = ParticipantSignup.objects.select_related('invitation__experiment_session',
                                                                   'invitation__participant').get(pk=data)
        except ParticipantSignup.DoesNotExist:
            raise forms.ValidationError(_("No signup found with pk %s" % data))
        return data


class ExperimentSessionForm(forms.ModelForm):
    def __init__(self, post_dict=None, instance=None, pk=None, user=None, **kwargs):
        if instance is None and pk is not None and pk != '-1':
            instance = ExperimentSession.objects.get(pk=pk)
        super(ExperimentSessionForm, self).__init__(post_dict, instance=instance, **kwargs)
        self.user = user
        if post_dict:
            self.request_type = post_dict.get('request_type')

    def save(self, commit=True):
        es = super(ExperimentSessionForm, self).save(commit=False)
        if self.request_type == 'delete':
            logger.warn("Deleting experiment session %s", es)
            es.delete()
        else:
            es.creator = self.user
            if commit:
                es.save()
        return es

    class Meta:
        model = ExperimentSession
        exclude = ('creator', 'date_created', 'invitation_text')


class SessionInviteForm(forms.Form):
    GENDER_CHOICES = (('A', 'All'), ('M', 'Male'), ('F', 'Female'),)

    number_of_people = forms.IntegerField(
        help_text=_("Number of participants to invite to the selected experiment session(s)"),
        widget=NumberInput(attrs={'value': 0, 'class': 'input-mini'}))
    only_undergrad = forms.BooleanField(
        help_text=_("Limit to self-reported undergraduate students"),
        widget=CheckboxInput(attrs={'checked': True}), required=False)
    port_of_mars = forms.BooleanField(
        help_text=_("Limit to Port of Mars Signups"),
        required=False
    )
    gender = forms.ChoiceField(choices=GENDER_CHOICES)
    affiliated_institution = forms.ModelChoiceField(
        queryset=Institution.objects.all(),
        required=False,
        initial=1,
        widget=autocomplete.ModelSelect2(
            url='core:institution-autocomplete',
            attrs={
                'data-placeholder': 'Institution name',
                'data-minimum-input-length': 3,
            }
        )
    )
    invitation_subject = forms.CharField(widget=widgets.TextInput())
    invitation_text = forms.CharField(widget=widgets.Textarea(attrs={'rows': '4'}))


class ParticipantAttendanceForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(ParticipantAttendanceForm, self).__init__(*args, **kwargs)
        self.fields['attendance'].widget.attrs['class'] = 'form-control input-sm'

    class Meta:
        model = ParticipantSignup
        fields = ['attendance']

vcweb/core/templates/base.html
{% load tags %}
{% load static %}
{% load bootstrap3 %}
{% url 'about' as about_url %}
{% url 'home' as home_url %}
{% url 'cas_login' as cas_login_url %}
{% url 'core:contact_form' as contact_url %}
{% url 'core:ostromlab_faq' as faq_url %}
{% url 'core:dashboard' as dashboard_url %}
{% url 'core:login' as login_url %}
{% url 'core:logout' as logout_url %}
{% url 'core:participate' as participate_url %}
{% url 'core:profile' as profile_url %}
{% url 'core:register' as register_url %}
{% url 'core:report_issues' as issues_url %}
{% url 'core:audit_report' as audit_report_url %}
{% url 'subjectpool:subjectpool_index' as subjectpool_url %}
<!DOCTYPE html>
<html lang="en">
{% with bootstrap_version="3.3.7" bootswatch_version="3.3.7" fontawesome_version="4.7.0" knockout_version="3.4.0" path=request.path %}
<head>
{% block head %}
<title>{% block title %}Virtual Commons Web Experiment{% endblock %}</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name='viewport' content='width=device-width, initial-scale=1'>
{% comment %}
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/{{bootswatch_version}}/spacelab/bootstrap.min.css">
{% endcomment %}
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/{{bootstrap_version}}/css/bootstrap.min.css">
<link rel='stylesheet' href="//maxcdn.bootstrapcdn.com/font-awesome/{{fontawesome_version}}/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'css/style.css' %}" media="screen">
<link href='//fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
{% endblock %}
</head>
<body>
{% block header %}
<nav class='navbar navbar-default navbar-fixed-top' role='navigation'>
    <div class='container'>
        {% block headernav %}
        {% block headerlinks %}
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class='navbar-brand {{ path|active:home_url }}' href='{{ home_url }}'><img class='pull-left' src='{% static "images/vcweb-logo.png" %}' width='30' height='23' alt='the virtual commons'>virtual commons </a>
        </div>
        <div class="collapse navbar-collapse" role='navigation'>
            <ul class='nav navbar-nav'>
                {% if user.is_authenticated %}
                    {% if user.participant %}
                        <li class='{{ path|active_re:participate_url }}'><a href='{{ participate_url }}'><i class='fa fa-users'></i> Participate</a></li>
                    {% elif user.experimenter %}
                        <li class='{{ path|active_re:dashboard_url }}'><a href='{{ dashboard_url }}'><i class='fa fa-tachometer'></i> Dashboard</a></li>
                        {% if not user.experimenter.is_demo_experimenter %}
                            <li class='{{ path|active_re:subjectpool_url }}'><a href='{{ subjectpool_url }}'><i class='fa fa-users'></i> Subject recruitment</a></li>
                        {% endif %}
                    {% endif %}
                {% endif %}
                <li class='{{ path|active:contact_url }}'><a href='{{ contact_url }}'><i class='fa fa-bell-o'></i> Contact us</a></li>
                <li><a target='_blank' href='{{ issues_url }}'><i class='fa fa-bullhorn'></i> Report a bug</a></li>
                {% comment %} <li><a href='#' id="report-issue" data-toggle="modal" data-target="#bugModal" ><i class='fa fa-bullhorn'></i> Report a bug</a></li> {% endcomment %}
            </ul>
            {% endblock headerlinks %}
            {% block login %}
            <ul class='nav navbar-nav navbar-right'>
                {% if user.is_authenticated %}
                <li class='{{ path|active:login_url }} dropdown'>
                <a class='dropdown-toggle' data-toggle='dropdown' href='#'>{{ user.email }} <i class='fa fa-chevron-down'></i></a>
                    <ul class='dropdown-menu'>
                        {% if user.is_superuser %}
                            <li><a href='{{ audit_report_url }}'><i class='fa fa-pie-chart'></i> Audit Report</a></li>
                        {% endif %}
                        <li><a href='{{ profile_url }}'><i class='fa fa-user'></i> Account</a></li>
                        <li><a href='{{ logout_url }}'><i class='fa fa-sign-out'></i> Sign out</a></li>
                    </ul>
                </li>
                {% else %}
                <li class='{{ path|active:login_url }}'>
                    <a href='{{ login_url }}'>
                        <i class='fa fa-sign-in'></i> Sign In
                    </a>
                </li>
                {% endif %}
            </ul>
            {% endblock login %}
            {% endblock headernav %}
        </div>
    </div>
</nav>
{% endblock %}
<div class='container fill'>
    <noscript>
        <div class='alert alert-danger alert-block'>
            <p>Please <b>enable JavaScript</b> if you'd like to use this site.
            <p>Experiments will not function properly without JavaScript enabled.</p>
        </div>
    </noscript>
    {% if DEBUG %}
    <div class='alert alert-danger alert-block devserver'>
        <h2>Development Server</h2>
        <i class='fa fa-exclamation-triangle fa-2x'></i>You are accessing a <b>development version</b> of vcweb. We periodically cleanse the database so any data you generate on this site should be considered transient.
    </div>
    {% endif %}
    {% if messages %}
        <h3>Messages</h3>
        {% bootstrap_messages %}
    {% endif %}

    {% block page %}
    <div class='row' id='page'>
        <div id='content' class='col-md-9'>
            {% block content %}
            {% endblock %}
        </div>
        <div id='sidebar' class='col-md-3 filler sidebar'>
            {% block sidebar %}
            {% endblock %}
        </div>
    </div>
    {% endblock page %}
</div>
<footer id="footer">
    {% block footer %}
    <div class='container'>
        {% block footerlinks %}
        <ul class='nav-footer hidden-xs'>
            <li><a href='https://cbie.asu.edu'>Center for Behavior, Institutions, and the Environment</a></li>
            <li><a href='https://complexity.asu.edu'>Biosocial Complexity Initiative @ ASU</a></li>
            <li><a href='http://www.azregents.edu/'>&copy; 2011-{% now "Y" %} Arizona Board of Regents</a></li>
            <li><a href='https://github.com/virtualcommons/vcweb'><i class='fa fa-github-square'></i> build: {{ RELEASE_VERSION }}</a></li>
        </ul>
        <a style='margin-top: 15px;' class='visible-xs pull-right' href='{{home_url}}'><img class='logo' src='{% static "images/vcweb-logo.png" %}' width='30' height='23' alt='vcweb logo'/></a>
        <ul style='margin-top: 5px;' class='list-unstyled visible-xs'>
            <li><a href='http://cbie.asu.edu'>Center for Behavior, Institutions, and the Environment</a>
            <li><a href='http://complexity.asu.edu'>Biosocial Complexity Initiative @ ASU</a></li>
            <li><a href='http://www.azregents.edu/'>&copy; 2011-{% now "Y" %} Arizona Board of Regents</a>
        </ul>
        {% endblock footerlinks %}
    </div>
    <div class="modal fade" id="bugModal" tabindex="-1" role="dialog" aria-labelledby="bugModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id='bugModalLabel'>Report Bug</h4>
                </div>
                <div class="modal-body"></div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    {% endblock footer %}
</footer>
    <!-- Latest compiled and minified JavaScript -->
    <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/{{bootstrap_version}}/js/bootstrap.min.js"></script>
    <script src='{% static "js/bootbox.min.js" %}'></script>
    <script src='{% static "js/jquery.cookie.js" %}'></script>
    <script src='//cdnjs.cloudflare.com/ajax/libs/knockout/{{knockout_version}}/knockout-min.js'></script>
    <script src='{% static "js/ko/knockout.mapping.min.js" %}'></script>
    <script src='{% static "js/ko/knockout.helper.js" %}'></script>
    <script src='{% static "js/common.js" %}'></script>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
         (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
         m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
         })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-321755-10', 'auto');
        ga('send', 'pageview');
    </script>
    {% block javascript %}
    {% endblock %}
</body>
{% endwith %}
</html>

vcweb/core/templates/cas_access_forbidden.html
{% extends "base.html" %}

{% block title %}
    Closed Registration
{% endblock %}

{% block page %}
    <h2>Access Forbidden</h2>
    <div class='entry'>
         Registration for VCWEB is limited to undergraduate students at the moment. Please 
         <a href='http://commons.asu.edu/contact'>contact us</a> if you'd like to learn more.
    </div>
{% endblock page %}

vcweb/core/templates/github-issue.html
**User: {{ user_id }}** had an issue at {{ url }}

More details about error:
{{ issue_text }}

vcweb/core/templates/invalid_request.html
{% extends "base.html" %}

{% block title %}
    Invalid Request
{% endblock %}

{% block page %}
    <div class='panel panel-default'>
        <div class='panel-heading'><h3 class='panel-title'>Invalid Request</h3></div>
        <div class='panel-body alert-warning'>
            <i class='fa fa-exclamation-triangle text-danger'></i> {{ message|default:"We couldn't complete your request. " }}
            Please <a href='/contact'>contact us</a> if this is an error on our end.
        </div>
    </div>
{% endblock page %}